### ISSUE TITLE
Show codes in app

### ISSUE THREAD

**Issue by quassy** [bil-elmoussaoui/TwoFactorAuth#2]
The app could be used to input codes in other devices (e.g. login to Facebook on mobile) so the app should display the currently generated code after clicking the copy icon for some time (WinAuth displays each code for 10s).

**Comment by bil-elmoussaoui** [comment]
You can use `Enter` as a keyboard shortcut to show the code, i will add a double click event too. The copy icon only copies the code to clipboard

**Comment by quassy** [comment]
`Enter` doesn't seem to work for me (nothing happens). Why not copy the code *and* show code (inplace of the minus and copy button) when clicking the copy button?

**Comment by bil-elmoussaoui** [comment]
The minus is for removing the secret code, i don't know if it's a good idea to remove it? but the user still can select a code an remove it...

**Comment by quassy** [comment]
The idea is that the copy and remove button reappear after 10s (and the current code disappears again).

**Comment by bil-elmoussaoui** [comment]
Ah okey :p so you wan't to have only a show button, once you click on it the code, the remove and the copy buttons are shown for like 10s?

**Comment by quassy** [comment]
The other way round :laughing: 

`Google [minus] [copy]`, then click on copy and for 10 seconds `Google 133337` is displayed, after that the view as it is now.

**Comment by bil-elmoussaoui** [comment]
Ah i will do that :D

**Comment by bil-elmoussaoui** [comment]
It should work perfectly now :) the code is shown for 10 seconds. Once i fix the rest of the issues i will make it configurable
