### ISSUE TITLE
Store credentials in secure store

### ISSUE THREAD

**Issue by emersion** [bil-elmoussaoui/TwoFactorAuth#4]
Right now all is saved without encryption on disk. Use a secure store instead.

Replace the lock/unlock feature by a password on the secure store.

**Comment by bil-elmoussaoui** [comment]
Thanks for the suggestion! I will do soon :+1:

**Comment by emersion** [comment]
You can use something like GNOME Keyring. See http://mindbending.org/en/series/bending-gnome-keyring-with-python

**Comment by bil-elmoussaoui** [comment]
Fixed in 39f51505bd72aed042529490239f6e50c6447675, i stored the secret codes, encrpyted with a md5 alogrithm and used it as an id for Gnome Keyring
It's might not be perfect, if there's any other issue don't hesitate to report it.
