### ISSUE TITLE
Add AUR package

### ISSUE THREAD

**Issue by emersion** [bil-elmoussaoui/TwoFactorAuth#7]
Add new `gnome-twofactorauth` package to AUR.

**Comment by bil-elmoussaoui** [comment]
Never done that before! I will see what i can do :)

**Comment by emersion** [comment]
You can start from an existing package, e.g. https://aur.archlinux.org/cgit/aur.git/tree/?h=gnome-music-git

Here is the official guide: https://wiki.archlinux.org/index.php/creating_packages

**Comment by bil-elmoussaoui** [comment]
Added the git version `gnome-twofactorauth-git`.
Once a stable version is released i will add a `gnome-twofactorauth` package

**Comment by emersion** [comment]
Cool :D

I think you've just made a typo because the dependency `python-cairo` has a trailing comma and I'm getting:
```
==> Building and installing package
==> Install or build missing dependencies for gnome-twofactorauth-git: 
error: target not found: python-cairo,
==> Restart building gnome-twofactorauth-git ? [y/N]
==> ------------------------------------------------
==> ^C
```

**Comment by bil-elmoussaoui** [comment]
Already fixed :+1: + i've added `python-pyotp` package build too so you won't need to install it manually

**Comment by emersion** [comment]
:ok_hand: Perfect, thanks a lot!

**Comment by bil-elmoussaoui** [comment]
@emersion As you've proposed the `gnome-twofactorauth` package name; i was thinking of changing the name of the repo too. What do you think? :)

**Comment by emersion** [comment]
Yes I think that will ne better, just `twofactorauth` is too generic. Also change the command name.

**Comment by bil-elmoussaoui** [comment]
@emersion Done :+1: I've fixed all the bugs i've ever had, can you try the latest git version and report back so i can see if it's time to release a stable version?
